const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '25,990',
        image: 'image/tv.jpg',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '52,499',
        image: 'image/laptop.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '5,995',
        image: 'image/watch.jpg',
        cat: 'watch',
        type: 'new',
    },
    {
        id: 4,
        Name: 'product4',
        price: '75,500',
        image: 'image/laptop1.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 5,
        Name: 'product5',
        price: '1800',
        image: 'image/speaker.jpg',
        cat: 'speaker',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '4000',
        image: 'image/electronics.jpg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'product7',
        price: '1900',
        image: 'image/headphone.jpg',
        cat: 'headphone',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'product8',
        price: '3000',
        image: 'image/electronics1.jpg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'product9',
        price: '65,999',
        image: 'image/phone.jpg',
        cat: 'phone',
        type: 'top',
    },
    {
        id: 10,
        Name: 'product10',
        price: '60,000',
        image: 'image/ac.jpg',
        cat: 'Ac',
        type: 'top',
    },
    {
        id: 11,
        Name: 'product11',
        price: '120',
        image: 'image/led.jpg',
        cat: 'ledlight',
        type: 'top',
    },
    {
        id: 12,
        Name: 'product12',
        price: '20,000',
        image: 'image/camera.jpg',
        cat: 'camera',
        type: 'top',
    },
]
export default Homeproduct